# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy MZ to AZURE

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envKey_TWITCH_CLIENT_ID: ${{ secrets.TWITCH_CLIENT_ID }}
          envKey_TWITCH_CLIENT_SECRET: ${{ secrets.TWITCH_CLIENT_SECRET }}
          envkey_TWITCH_CHANNELS: ${{ secrets.TWITCH_CHANNELS }}
          envkey_TWITCH_USER_ID: ${{ secrets.TWITCH_USER_ID }}
          envkey_TWITCH_ROOM_ID: ${{ secrets.TWITCH_ROOM_ID }}
          envKey_MONGODB_URI: ${{ secrets.MONGODB_URI }}
          envKey_AEMET_API_KEY: ${{ secrets.AEMET_API_KEY }}
          envkey_PORT: 3000
          envkey_TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          envKey_TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          envKey_EXTERNAL_URL: ${{ secrets.EXTERNAL_URL }}
          envKey_BROWSERLESS_URL: ${{ secrets.BROWSERLESS_URL }}
          envKey_BROWSERLESS_TOKEN: ${{ secrets.BROWSERLESS_TOKEN }}
          envKey_BROWSERLESS_VERSION: v1
          envKey_STATUS_URL: ${{ secrets.STATUS_URL }}
          envKey_WHITE_LIST_ADMINS: ${{ secrets.WHITE_LIST_ADMINS }}
          envKey_WHITE_LIST_EDITORS: ${{ secrets.WHITE_LIST_EDITORS }}
          envKey_FEATURE_TF_SPOTS: false
      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present

      - name: Zip artifact for deployment
        run: zip -r release.zip * .env

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'twitch-mz-bot'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_5F8104D0F0DB4488AE974F3659C5C153 }}
          package: release.zip
